/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Donation = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'note' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'amount' : IDL.Text,
  'screenshot' : IDL.Text,
});
export const MemberApplication = IDL.Record({
  'id' : IDL.Nat,
  'occupation' : IDL.Text,
  'status' : IDL.Text,
  'paymentScreenshot' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'paymentDone' : IDL.Bool,
  'phone' : IDL.Text,
  'photo' : IDL.Text,
});

export const idlService = IDL.Service({
  'approveMemberApplication' : IDL.Func([IDL.Nat], [], []),
  'clearAllDonations' : IDL.Func([], [], []),
  'confirmMemberPayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteDonationById' : IDL.Func([IDL.Nat], [], []),
  'deleteMemberApplication' : IDL.Func([IDL.Nat], [], []),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAllMemberApplications' : IDL.Func(
      [],
      [IDL.Vec(MemberApplication)],
      ['query'],
    ),
  'getMemberByPhoneAndName' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(MemberApplication)],
      ['query'],
    ),
  'submitDonation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitMemberApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitPaymentProof' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Donation = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'note' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'amount' : IDL.Text,
    'screenshot' : IDL.Text,
  });
  const MemberApplication = IDL.Record({
    'id' : IDL.Nat,
    'occupation' : IDL.Text,
    'status' : IDL.Text,
    'paymentScreenshot' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'paymentDone' : IDL.Bool,
    'phone' : IDL.Text,
    'photo' : IDL.Text,
  });
  
  return IDL.Service({
    'approveMemberApplication' : IDL.Func([IDL.Nat], [], []),
    'clearAllDonations' : IDL.Func([], [], []),
    'confirmMemberPayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteDonationById' : IDL.Func([IDL.Nat], [], []),
    'deleteMemberApplication' : IDL.Func([IDL.Nat], [], []),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAllMemberApplications' : IDL.Func(
        [],
        [IDL.Vec(MemberApplication)],
        ['query'],
      ),
    'getMemberByPhoneAndName' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(MemberApplication)],
        ['query'],
      ),
    'submitDonation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitMemberApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitPaymentProof' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };