/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Donation = IDL.Record({
  'name' : IDL.Text,
  'note' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'amount' : IDL.Text,
  'screenshot' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'submitDonation' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'clearAllDonations' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Donation = IDL.Record({
    'name' : IDL.Text,
    'note' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'amount' : IDL.Text,
    'screenshot' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'submitDonation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'clearAllDonations' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };