/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Donation = IDL.Record({
  'name' : IDL.Text,
  'note' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'amount' : IDL.Text,
  'screenshot' : IDL.Text,
});

export const MemberApplication = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'address' : IDL.Text,
  'occupation' : IDL.Text,
  'photo' : IDL.Text,
  'status' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'submitDonation' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'clearAllDonations' : IDL.Func([], [], []),
  'deleteDonationById' : IDL.Func([IDL.Nat], [], []),
  'submitMemberApplication' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllMemberApplications' : IDL.Func([], [IDL.Vec(MemberApplication)], ['query']),
  'approveMemberApplication' : IDL.Func([IDL.Nat], [], []),
  'deleteMemberApplication' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Donation = IDL.Record({
    'name' : IDL.Text,
    'note' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'amount' : IDL.Text,
    'screenshot' : IDL.Text,
  });
  const MemberApplication = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'address' : IDL.Text,
    'occupation' : IDL.Text,
    'photo' : IDL.Text,
    'status' : IDL.Text,
    'timestamp' : Time,
  });
  return IDL.Service({
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'submitDonation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'clearAllDonations' : IDL.Func([], [], []),
    'deleteDonationById' : IDL.Func([IDL.Nat], [], []),
    'submitMemberApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllMemberApplications' : IDL.Func([], [IDL.Vec(MemberApplication)], ['query']),
    'approveMemberApplication' : IDL.Func([IDL.Nat], [], []),
    'deleteMemberApplication' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
