/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DonationWithScreenshot {
  'name' : string,
  'note' : string,
  'timestamp' : Time,
  'phone' : string,
  'amount' : string,
  'screenshot' : string,
}
export interface MemberApplication {
  'id' : bigint,
  'occupation' : string,
  'status' : string,
  'name' : string,
  'address' : string,
  'timestamp' : Time,
  'paymentDone' : boolean,
  'phone' : string,
  'photo' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'approveMemberApplication' : ActorMethod<[bigint], undefined>,
  'clearAllDonations' : ActorMethod<[], undefined>,
  'confirmMemberPayment' : ActorMethod<[bigint], boolean>,
  'deleteDonationById' : ActorMethod<[bigint], undefined>,
  'deleteMemberApplication' : ActorMethod<[bigint], undefined>,
  'getAllDonations' : ActorMethod<[], Array<DonationWithScreenshot>>,
  'getAllMemberApplications' : ActorMethod<[], Array<MemberApplication>>,
  'getMemberByPhoneAndName' : ActorMethod<
    [string, string],
    [] | [MemberApplication]
  >,
  'submitDonation' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitMemberApplication' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];